step 2
MrSpooner/react-burger pull request #1
Opened 2023-05-11 15:51 UTC by MrSpooner

2023-05-11 16:20 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Проект соответствует макету
- Хорошая декомпозиция компонентов
- Хорошо разобрались с `propTypes`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Вверху и внизу конструктора должны быть одинаковые булки. 
- У верхней и нижней булки должны быть надписи "Верх" и "Низ" соответственно.
- Ограничьте высоту конструктора и списка ингредиентов - посмотрите как в фигме.
- Вы используете сейчас две технологии `typescript` и `propTypes` необходимо оставить одну. Рекомендую `propTypes` - для этого все расширения файлов должны быть `jsx` а не `tsx `
- Добавьте проверку успешности запроса
- Запрос необходимо делать в компоненте `App` и оттуда передавать в дочерние компоненты
- У модалки должна быть полупрозранчая подложка на заднем фоне.
- В консоли есть ошибка связанная с `propTypes`
- у `ModalOverlay` не должно быть `children`, это просто компонент подложки а не контейнер
- вынесите магическое значение 27 в именованную константу

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-11 16:20 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.tsx
> +        const getProductData = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-05-11 16:20 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.tsx
> +                .then((res) => res.json())
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-05-11 16:20 UTC, andryxxa93 commented on src/components/burger-ingredients-tab/burger-ingredients-tab.tsx
> +    data: PropTypes.arrayOf(
**Надо исправить**

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать

2023-05-11 16:20 UTC, andryxxa93 commented on src/components/modal-ingredient-details/ingredient-details.tsx
> +IngredientDetails.propTypes = {
**Необходимо исправить**
Тут есть ошибка в `propTypes` - её можно увидеть в консоли разработчика в браузере - F12

2023-05-11 16:20 UTC, andryxxa93 commented on src/components/modal-overlay/modal-overlay.tsx
> +        {data.data.type === 'ingredients' ? <IngredientDetails data={data.data.data}/> : <OrderDetails/>}
**Необходимо исправить**
Необходимо делать компоненты максимально универсальными. Сейчас получается, что модалку можно использовать только в двух случаях - показывая или `IngredientDetails ` или `OrderDetails `. Если понадобится показать что-то ещё, то придется менять условие, усложнять код - это не правильно. Необходимо просто оборачивать модалкой необходимые компоненты. Делать это нужно в конструкторе и в списке ингредиентов. 

```
<Modal onClose={onClose}>
  <IngredientDetails ingredient={ingredient} />
</Modal>
```

2023-05-11 16:20 UTC, andryxxa93 commented on src/components/modal/modal.tsx
> +        if (event.keyCode === 27) {
**Надо исправить**

вынесите магическое значение 27 в именованную константу `const ECK_KEYCODE = 27`

2023-05-11 16:20 UTC, andryxxa93 commented on src/components/modal/modal.tsx
> +            document.removeEventListener("keydown", onKeyDown);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-05-11 16:20 UTC, andryxxa93 commented on src/utils/data.js
> +const Data = [
**Можно лучше**
Файл больше не нужен - его можно удалить

2023-05-14 08:21 UTC, andryxxa93 commented
**Необходимо исправить**
- Ограничьте высоту конструктора и списка ингредиентов - посмотрите как в фигме.
- Булки не должны скролиться, скролиться должны только ингредиенты между ними
- У вас в коде есть `debugger`
- У модалки должна быть полупрозранчая подложка на заднем фоне. Вы сделали саму модалку полупрозрачной, но это подложка за ней должна быть такой. Посмотрите как в фигме.
- Так же модалка должна закрываться при нажатии на задний фон.

2023-05-14 15:28 UTC, MrSpooner commented
Высота конструктора и списка ингредиентов ограничена, у самой модалки нет стилей

2023-05-15 06:50 UTC, andryxxa93 commented
**Необходимо исправить**
Сам компонент модалки - это информация о заказа или ингредиенте и фон под ней. А вот всё что обрамляет модалку, т.е. находится на заднем фоне и создаёт затемнение основного контента страницы - это `ModalOverlay`.
На скриншоте видно как должно выглядеть.

<img width="1440" alt="Снимок экрана 2023-05-15 в 09 47 16" src="https://github.com/MrSpooner/react-burger/assets/60173362/fd87a791-0731-4278-9f01-3dfb8a8b821b">

2023-05-15 10:07 UTC, MrSpooner commented
Теперь стилизация подложки отдельно в компоненте modaloverlay
и стилизация окна отдельно в modal

2023-05-15 17:25 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-16 07:25 UTC, merged